Develop
egovernments/punjab-mgramseva pull request #411
Opened 2023-05-29 04:13 UTC by debasishchakraborty-egovt

2023-06-08 09:03 UTC, naveen-egov requested changes
most of the file name are not in snack case  (lowercase letters and underscores between words.) kindly make those  changes

2023-06-08 09:03 UTC, naveen-egov commented on frontend/mgramseva/lib/screeens/AddExpense/AddExpenseWalkThrough/expenseWalkThrough.dart
> +import 'package:mgramseva/widgets/AutoCompleteView.dart';
+1

2023-06-12 09:01 UTC, rahuldevgarg-egov commented on frontend/mgramseva/lib/repository/forgot_password_repo.dart
> +import 'package:mgramseva/services/BaseService.dart';
https://github.com/egovernments/punjab-mgramseva/pull/426

2023-06-16 04:41 UTC, naveen-egov approved these changes

2023-06-16 04:41 UTC, naveen-egov commented on frontend/mgramseva/lib/components/notifications/notifications_list_1.dart
Why the file name is 1.dart

2023-06-16 04:41 UTC, naveen-egov commented on frontend/mgramseva/lib/screeens/consumer_details/consumer_details_walk_through/walkthrough_1.dart
Why is it sufix 1 appended to the file name.

2023-06-16 04:43 UTC, rahuldevgarg commented on frontend/mgramseva/lib/components/notifications/notifications_list_1.dart
this is duplicate file with minor change

2023-06-16 04:43 UTC, rahuldevgarg commented on frontend/mgramseva/lib/screeens/consumer_details/consumer_details_walk_through/walkthrough_1.dart
this is duplicate file with minor change

2023-06-16 05:06 UTC, egov-arindam approved these changes

2023-06-16 05:07 UTC, merged